import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/NavbarComponent";
import SidebarComponent from "@/components/SidebarComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="grid grid-cols-11 grid-flow-col gap-20 bg-gray-200 h-screen overflow-auto">
          <div className="col-span-2 bg-white">
            <SidebarComponent />
          </div>

          <div className=" col-span-9  grid grid-rows-6 ">
            <div className="  row-span-1 ">
              <NavbarComponent />
            </div>
            <div className="row-span-5 ">
              {children}
            </div>

          </div>
        </div>
      </body>
    </html>
  );
}
